[workspace]
members = ["pam", "examples/basic-auth"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["Anthony Nowell <anowell@gmail.com>", "Abran DeCarlo <abrandecarlo@protonmail.com>"]
publish = false
