[package]
name = "basic-auth"
version = "0.0.1"
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
publish = false

[lib]
name = "basic_auth"
crate-type = ["cdylib"]

[dependencies]
pam-bindings = { path = "../../" }